name: Build debug apk

on:
  workflow_dispatch # 保持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # 可以一并升级到 v4

      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11.0.30+7'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      # 执行完整的构建和打包。assembleDebug 会编译并生成 APK
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # 关键修改：将上传 artifact 的 action 升级到 v4
      - name: Upload debug apk
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug